# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in
include ../../oss.in

# 定义输出规则
OUTPUT_OBJ = libr4_440_m
LINK_LIB   = -lr4_440 -lformat -ltoolbase
include ../../dll.in
include ../../rule.in
