# iGateway Bill V200 ap 部分makefile
# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in

# 定义输出规则
OUTPUT_OBJ = ap_proc
LINK_LIB = -lnetbase -lfrontsave -lconvert -lbacksave -lmerge -lformat -lframe -lcomm -ltoolbox -ltoolbase
include ../../app.in
include ../../rule.in

