# iGateway Bill V200R002B02 cls_proc Makefile
# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in

# 定义输出规则
OUTPUT_OBJ = cls_proc
LINK_LIB = -lagent -lframe -lcomm -ltoolbox -ltoolbase
include ../../app.in
include ../../rule.in
