# iGateway Bill V200 collector 部分makefile
# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in

# 定义输出规则
OUTPUT_OBJ = co_proc
LINK_LIB = -lcollector -lcolconvertor -lformat -lframe -lcomm -ltoolbox -ltoolbase
include ../../app.in
include ../../rule.in
