# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in
include ../../oss.in

# 定义输出规则
OUTPUT_OBJ = libr98_760_m
LINK_LIB   = -lr98_760 -lformat -ltoolbase
include ../../dll.in
include ../../rule.in
