# iGateway Bill V200R002B02 mmlcmd Makefile
# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in

# 定义输出规则
OUTPUT_OBJ = mml_cmd
LINK_LIB = -ltoolbox -ltoolbase
include ../../app.in
include ../../rule.in
