# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in
include ../../oss.in

# 定义输出规则
OUTPUT_OBJ = lib3g_cs_asn1
LINK_LIB   = -ltoolbase
include ../../dll.in
include ../../rule.in
