# iGateway Bill V200R002B02 bs_proc Makefile
# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in

# 定义输出规则
OUTPUT_OBJ = bs_proc
LINK_LIB =  -lframe -lcomm -ltoolbox -ltoolbase -lcdrsender
include ../../app.in
include ../../rule.in
