# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in
include ../../oss.in

# 定义输出规则
OUTPUT_OBJ = libr98_770
LINK_LIB   = -lformat -lmerge -ltoolbase
include ../../dll.in
include ../../rule.in
