# 定义编译器和编译开关
include ../../platform.in
include ../../debug.in
include ../../product.in
include ../../oss.in

# 定义输出规则
OUTPUT_OBJ = libr99_3a0_m
LINK_LIB   = -lr99_3a0 -lformat -ltoolbase
include ../../dll.in
include ../../rule.in
